# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            butterbutt
tagline:          '(trying to) make art with python'
description:      'my journey learning python following the book <a href="https://www.makeartwithpython.com/"><I>Make Art With Python</I></a> by Kirk Kaiser.'
url:              http://hyde.getpoole.com
baseurl:          '/learningdiery/'

author:
  name:           'Stacey tsui'
  url:            https://twitter.com/tsuistacey/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://nocopyandpaste.github.io/homework
