# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            de-press stacey
tagline:          ' '
description:      'journal of what i try to do after i got de-press-ed in hong kong to not get depressed.'
url:              https://stayteef.github.io
baseurl:          /
root:             /

author:
  name:           'Stacey tsui'
  url:            'https://twitter.com/tsuistacey/'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           'https://github.com/stayteef/stayteef.github.io'
